spring:
  application:
    name: exchange-service

  datasource:
    url: jdbc:postgresql://localhost:5432/exchange-service
    username: postgres
    password: 1234567

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#        hbm2ddl:
#          delimiter: ;
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql

    hibernate:
      ddl-auto: update

    show-sql: true

    open-in-view: false

  flyway:
    url: jdbc:postgresql://localhost:5432/exchange-service
    user: postgres
    password: 1234567

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      base-path: /exchange-service/actuator
      exposure:
        include: '*'

  tracing:
    sampling:
      probability: 1

server:
  port: 8000

springdoc:
  api-docs:
    path: /exchange-service/v3/api-docs