spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765

management:
  endpoints:
    web:
      base-path: /exchange-service/actuator
      exposure:
        include: '*'

  tracing:
    sampling:
      probability: 1

springdoc:
  swagger-ui:
    urls:
      - url: /book-service/v3/api-docs
        name: Book Service
      - url: /exchange-service/v3/api-docs
        name: Exchange Service