spring:
  application:
    name: config-server

#  profiles:
#    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/leandrocgsi/erudio-config-server.git
          search-paths: "greeting-service*"

server:
  port: 8888
