name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
